OK = {'code': 200, 'message':'Ok'}
CREATED = {'code': 201, 'message':'Created'}
ACCEPTED = {'code': 202, 'message':'Accepted'}
NO_CONTENT = {'code': 204, 'message':'No Content'}
BAD_REQUEST = {'code': 400, 'message':'Bad request'}
UNAUTHORIZED = {'code': 401, 'message':'Unauthorized'}
FORBIDDEN = {'code': 403, 'message':'Forbidden'}
CREATED = {'code': 200, 'message':'Ok'}
NOT_FOUND = {'code': 404, 'message':'Not Found'}
METHOD_NOT_ALLOWED = {'code': 405, 'message':'Method Not Allowed'}
INTERNAL_ERROR_SERVER = {'code': 500, 'message':'Internal server error' }
BAD_GATEWAY = {'code': 502, 'message':'Bad Gateway'}
SERVICE_UNAVAILABLE = {'code': 503, 'message':'Service Unavailable'}
GATEWAY_TIMEOUT = {'code': 504, 'message':'Gateway Timeout'}
HTTP_VERSION_NOT_SUPPORTED = {'code': 505, 'message':'HTTP Version Not Supported'}
ZION_RESPONSE_NOT_FOUND = {"estado": "USUARIO SIN PERFILES","mensaje": "El usuario no tiene perfiles asignados al sistema."}
ZION_RESPONSE_UNAUTHORIZED = {"estado": "CONTRASEÑA INCORRECTA","mensaje": "La contraseña es incorrecta."}
ZION_RESPONSE_NO_CONTENT = {"estado": "USUARIO INACTIVO","mensaje": "El usuario no se encuentra activo."}